// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzp8Q0bWyyQUnvXVUHK_hhU8Zv9wgY11s',
    appId: '1:372367270384:web:46f8a3eb95f9089222fd35',
    messagingSenderId: '372367270384',
    projectId: 'makki-muslim-2',
    authDomain: 'makki-muslim-2.firebaseapp.com',
    databaseURL: 'https://makki-muslim-2.firebaseio.com',
    storageBucket: 'makki-muslim-2.appspot.com',
    measurementId: 'G-NZPNK203W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWhhfaFBTzqOYldcoTGn7J0mqXAmZXe5M',
    appId: '1:372367270384:android:a3d70fffe632376222fd35',
    messagingSenderId: '372367270384',
    projectId: 'makki-muslim-2',
    databaseURL: 'https://makki-muslim-2.firebaseio.com',
    storageBucket: 'makki-muslim-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnKKeeH8cTa8QSKgvA5pr6Kxuuw_C_IIo',
    appId: '1:372367270384:ios:184083dddd62e5c722fd35',
    messagingSenderId: '372367270384',
    projectId: 'makki-muslim-2',
    databaseURL: 'https://makki-muslim-2.firebaseio.com',
    storageBucket: 'makki-muslim-2.appspot.com',
    iosBundleId: 'com.example.makkiTvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnKKeeH8cTa8QSKgvA5pr6Kxuuw_C_IIo',
    appId: '1:372367270384:ios:85e98c71627173c322fd35',
    messagingSenderId: '372367270384',
    projectId: 'makki-muslim-2',
    databaseURL: 'https://makki-muslim-2.firebaseio.com',
    storageBucket: 'makki-muslim-2.appspot.com',
    iosBundleId: 'com.example.makkiTvApp.RunnerTests',
  );
}
